config/routes.rb
Rails.application.routes.draw do
  # get 'documents/new'
  # get 'documents/create'
  # get 'documents/update'
  # get 'documents/edit'
  # get 'documents/destroy'
  # get 'documents/index'
  # get 'documents/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# DOCUMENTS CONTROLLER'S ROUTES

resources :documents

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  # belongs_to :dossier
  validates :name, :client, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_name_client_year_cabinet_and_matiere, against: [ :name, :year, :cabinet, :matiere, :client ],
      using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

Document.new.errors[:name].any? # => false

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR year ILIKE :query OR client ILIKE :query OR subject ILIKE :query OR localisation ILIKE :query"
      @documents = Document.where(sql_query, query: "%#{params[:query]}%")
    else
      @documents = Document.all
    end
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(allowed_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    @document.save
    redirect_to document_path(@document)
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = Document.find(params[:id])
    @document.update(allowed_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to document_path(@document)
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    # no need for app/views/documents/destroy.html.erb
    redirect_to documents_path
  end

  private

  def allowed_params
    params.require(:document).permit(:name, :client, :year, :localisation, :subject, :cabinet, :carton)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/edit.html.erb
<h1>Documents#edit</h1>
<p>Find me in app/views/documents/edit.html.erb</p>

<%= render '/shared/form', document: @document %>

app/views/documents/index.html.erb
<div class="container">
  <h1>Bienvenue !</h1>

  <!-- Chercher un document -->
  <p>Cherchez un document existant :</p>
  <%= form_tag documents_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Chercher un document"%>

    <%= submit_tag "Rechercher", class: "btn btn-primary" %>
    <% end %>

<!-- Lien vers création d'un document -->
<br>
<p>Ou référencez un nouveau document :</p>
    <%= link_to "Nouveau", "documents/new" %>
<!-- Index qui montre les documents OU documents recherchés -->
<!-- TODO2 : Ne faire un index qui ne fait que les documents recherchés -->

<% @documents.each do |document| %>
  <h2><%= document.name %></h2>
  <%= link_to "Supprimer", document, method: :delete, data: { confirm: "Voulez-vous vraiment supprimer ce document ?" } %>
  <%= link_to "Mettre à jour", edit_document_path(document) %>

<% end %>
</div>

app/views/documents/new.html.erb
<h1>Création de document</h1>
<p><em>Veuillez référencer le document</em></p>

<%= render '/shared/form', document: @document %>

app/views/documents/show.html.erb
<h1>Votre document a bien été référencé !</h1>
<p>Référencement sous le nom de :</p>
<h2><%= @document.name %></h2>


<%= link_to "Aller à l'accueil", documents_path %>

<%= link_to "Mettre à jour", edit_document_path(@document) %>

<%= form_tag document_path(@document.id), method: "delete" do %>
  <%= submit_tag "Delete #{@document.name}" %>
<% end %>

app/views/documents/update.html.erb
<h1>Documents#update</h1>
<p>Find me in app/views/documents/update.html.erb</p>

<%= render '/shared/form', document: @document %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="container">
  <%= form_for(@document) do |f| %>
  <div class="nom">
    <%= f.label :nom %>
    <%= f.text_field :name %>
  </div>
  <div class="client">
    <%= f.label :client %>
    <%= f.text_field :client %>
  </div>
  <div class="année">
    <%= f.label :année %>
    <%= f.select :year, (2000)..(Time.zone.now.year - 3) %>
  </div>
  <div class="matière">
    <%= f.label :matière %>
    <%= f.select :subject, ['01. Comptabilité', '02. Social', '03. Juridique', '04. Dossiers personnels', '05. Administratif'],prompt: 'Sélectionnez une matière' %>
  </div>
  <div class="carton">
    <%= f.label :carton %>
    <%= f.text_field :carton %>
  </div>
    <div class="localisation">
      <%= f.label :localisation %>
      <%= f.select :localisation,['SAINT-TROPEZ - étage', 'SAINT-TROPEZ - cave', 'SAINT-TROPEZ - garage', 'COGOLIN - RDC', 'COGOLIN - garage', 'MARSEILLE ACA - cave grande pièce', 'MARSEILLE ACA - cave pièce entrée', 'MARSEILLE ACA - cave pièce entrée', 'MARSEILLE ACA - cave pièce du fond', 'MARSEILLE ACA - cave passage du fond', 'MARSEILLE ACA - cave pièce chaudière', 'MARSEILLE ACA - petite pièce', 'PARIS - sous-sol', 'MARSEILLE SGCAM - pièce rangement'],prompt: 'Sélectionnez une localisation' %>
    </div>

    <%= f.submit %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li id="nav-item">
        <%= link_to "Authentification", new_user_session_path, class: "nav-link"%>
      </li>
      <% end %>
    </ul>
  </div>
</div>